### PR TITLE
Added safe navigation with method support

### PR DESCRIPTION
**Pull request by alexnask**
See [rock/47](https://github.com/magic-lang/rock/pull/47)

### CODE REVIEW

**Comment by thomasfanell** [comment]
I'm merging this in my #4, so i'll close this soon. There was a mess of nagaqueenish proportions, and it seems easier to do it this way for now.

**Comment by alexnask** [comment]
Ok :)  
Just make sure to merge after [rock/47](https://github.com/magic-lang/rock/pull/47) is merged itself.

**Comment by thomasfanell** [comment]
Of course :)

**Comment by thomasfanell** [comment]
And great job, by the way... much appreciated! :+1:

**Pull request merged**
